name: FF_unsupervised
channels:
  - pytorch
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pillow
  - python=3.8
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - scikit-learn
  - scipy
  - torchvision
  - tqdm
